### ISSUE TITLE
Error on laser tower shooting

### ISSUE THREAD

**Issue by neki-dev** [neki-dev/izowave#67]
**Error**
```
Cannot read properties of undefined (reading 'game')
```

**Trace**
```
TypeError: Cannot read properties of undefined (reading 'game')
    at wy.hit (https://izowave.neki.guru/index-daaeb379.js:6852:44309)
    at wy.processing (https://izowave.neki.guru/index-daaeb379.js:6852:44818)
    at wy.update (https://izowave.neki.guru/index-daaeb379.js:6852:43723)
    at initialize.preUpdate (https://izowave.neki.guru/index-daaeb379.js:1516:3679)
    at initialize.sceneUpdate (https://izowave.neki.guru/index-daaeb379.js:1144:572)
    at initialize.s.emit (https://izowave.neki.guru/index-daaeb379.js:1:6506)
    at initialize.step (https://izowave.neki.guru/index-daaeb379.js:4964:785)
    at initialize.update (https://izowave.neki.guru/index-daaeb379.js:4951:3257)
    at tS.step (https://izowave.neki.guru/index-daaeb379.js:466:1766)
    at initialize.step (https://izowave.neki.guru/index-daaeb379.js:470:2714)
```

**Comment by neki-dev** [comment]
Fixed at #73
