### ISSUE TITLE
Error on building action by UI

### ISSUE THREAD

**Issue by neki-dev** [neki-dev/izowave#68]
**Trace 1**
```
TypeError: Cannot read properties of undefined (reading 'player')
    at pu.repair (https://izowave.neki.guru/index-daaeb379.js:6852:21823)
    at Object.onClick (https://izowave.neki.guru/index-daaeb379.js:6852:20171)
    at HTMLDivElement.z (https://izowave.neki.guru/index-daaeb379.js:7578:79)
```

**Trace 2**
```
TypeError: Cannot read properties of undefined (reading 'wave')
    at cu.upgrade (https://izowave.neki.guru/index-d6cd8a4b.js:6824:20274)
    at Object.onClick (https://izowave.neki.guru/index-d6cd8a4b.js:6824:19287)
    at HTMLDivElement.W (https://izowave.neki.guru/index-d6cd8a4b.js:7533:79)
```

**Comment by neki-dev** [comment]
Fixed at #71
