### ISSUE TITLE
Error on fire tower shooting

### ISSUE THREAD

**Issue by neki-dev** [neki-dev/izowave#69]
**Error**
```
Cannot read properties of undefined (reading 'getEntities')
```

**Trace**
```
TypeError: Cannot read properties of undefined (reading 'getEntities')
    at ep.hit (https://izowave.neki.guru/index-1d70ed4d.js:6825:6717)
    at Function.<anonymous> (https://izowave.neki.guru/index-1d70ed4d.js:6825:5481)
    at initialize.collideSpriteVsSprite (https://izowave.neki.guru/index-1d70ed4d.js:4247:11234)
    at initialize.collideHandler (https://izowave.neki.guru/index-1d70ed4d.js:4247:10557)
    at initialize.collideObjects (https://izowave.neki.guru/index-1d70ed4d.js:4247:10035)
    at initialize.update (https://izowave.neki.guru/index-1d70ed4d.js:4203:297)
    at initialize.update (https://izowave.neki.guru/index-1d70ed4d.js:4247:4586)
    at s.emit (https://izowave.neki.guru/index-1d70ed4d.js:1:6506)
    at initialize.step (https://izowave.neki.guru/index-1d70ed4d.js:4964:785)
    at initialize.update (https://izowave.neki.guru/index-1d70ed4d.js:4951:3257)
```

**Comment by neki-dev** [comment]
Fixed at #73
